export const GET_WIDGETS = "GET_WIDGETS";
export const UPDATE_WIDGET = "UPDATE_WIDGET";
export const ADD_WIDGET = "ADD_WIDGET";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const UPDATE_WIDGETS_LAYOUT = "UPDATE_WIDGETS_LAYOUT";
