export const GET_SCRIPTS = "GET_SCRIPTS";
export const GET_SCRIPT = "GET_SCRIPT";
export const ADD_SCRIPT = "ADD_SCRIPT";
export const DELETE_SCRIPT = "DELETE_SCRIPT";
export const SET_KERNEL = "SET_KERNEL";
export const SET_KERNEL_EXECUTION_STATE = "SET_KERNEL_EXECUTION_STATE";
export const GET_LINKS = "GET_LINKS";
