export const UPLOADED_FILES_LOADING = "UPLOADED_FILES_LOADING";
export const GET_UPLOADED_FILES_SUCCESS = "GET_UPLOADED_FILES_SUCCESS";
export const GET_UPLOADED_FILES_ERROR = "GET_UPLOADED_FILES_ERROR";
export const DELETE_UPLOADED_FILE = "DELETE_UPLOADED_FILE";
export const UPDATE_UPLOADED_FILE = "UPDATE_UPLOADED_FILE";
export const ADD_UPLOADED_FILE = "ADD_UPLOADED_FILE";
