export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_STATUS = "UPLOAD_STATUS";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const RESET_UPLOAD_STATE = "RESET_UPLOAD_STATE";
