# Generated by Django 3.0.3 on 2020-02-26 10:52

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('title', models.TextField()),
                ('slug', models.TextField()),
                ('code', models.TextField(blank=True, default='[]', null=True)),
                ('notebook_file', models.TextField(blank=True, null=True)),
                ('script_file', models.TextField(blank=True, null=True)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('widgetUid', models.TextField()),
                ('widget_type', models.TextField()),
                ('cellUid', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('layout', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('visible', models.TextField(blank=True, null=True)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('parent_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('kernel_id', models.TextField()),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('parent_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.IntegerField()),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(default=1)),
                ('parent_organization_id', models.IntegerField(default=1)),
                ('uid', models.TextField()),
                ('config', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('parent_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Script')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
